-- Create Clients Table
create table public.clients (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text unique not null
);

-- Create Services Table
create table public.services (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date date not null,
  type text not null,
  value numeric not null,
  plate text not null,
  model text not null,
  owner text not null,
  client text not null
);

-- Set up Row Level Security (RLS)
-- For now, allowing all interaction for authenticated users
-- You can make this stricter (e.g., only own data) if you link 'client' to auth.users

alter table public.clients enable row level security;
alter table public.services enable row level security;

-- Policy: Allow full access to authenticated users
create policy "Allow all access for authenticated users" on public.clients
  for all using (auth.role() = 'authenticated');

create policy "Allow all access for authenticated users" on public.services
  for all using (auth.role() = 'authenticated');
